# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='{"course_1": "", "course_2": "", "course_3": "", "course_4": "", "course_5": "", "course_6": "", "course_7": "", "course_8": "", "course_9": "", "course_10": "", "course_11": "", "course_12": "", "course_13": "", "course_14": "", "course_15": "", "course_16": "", "course_17": "", "course_18": "", "course_19": "", "course_20": "", "course_21": "", "course_22": "", "course_23": "", "course_24": "", "course_25": "", "course_26": "", "course_27": "", "course_28": "", "course_29": "", "course_30": "", "course_31": "", "course_32": "", "course_33": "", "course_34": "", "course_35": ""}', max_length=10000)),
                ('organic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminManage.Organization')),
            ],
        ),
    ]
